"""
meme_stock_classifier.py  —  Inspirit AI · Meme Stock Investigator
===================================================================
Auto-generated by Notebook 3. Contains YOUR prompt, YOUR few-shot
examples, and YOUR flair mapping — personalized from this session.

Public API
----------
    classify_post(text, flair, client)   -> single-post classification
    classify_dataframe(df, client)       -> batch DataFrame classification
    load_labeled_data()                  -> loads wsb_labeled.csv
    get_sentiment_summary(df)            -> counts/pct dict for stat cards
    get_top_tickers(df, n)               -> hot-stocks leaderboard DataFrame
"""

import os, re, time, json
import pandas as pd
from openai import OpenAI, RateLimitError, APIError

MODEL         = 'gpt-5.4-mini'
RETRY_LIMIT   = 3
RETRY_DELAY   = 5
LABELS        = ("Positive", "Negative", "Neutral")
FAILURE_LABEL = "Unable to label"

BULLISH_MEME_KEYWORDS = {
    "strong": {"moon", "to the moon", "🚀", "diamond hands", "apes", "ape in", "ape strong", "hold",
               "hodl", "squeeze", "short squeeze", "gamma squeeze", "yolo", "tendies", "liftoff",
               "next gme", "next amc", "rocket", "blasting off", "we like the stock", "lfg", "let's go"},
    "medium": {"buy the dip", "loading", "accumulating", "retail", "coom", "degen", "based", "chad",
               "paper hands", "fomo", "going parabolic", "infinity squeeze"}
}

BEARISH_MEME_KEYWORDS = {
    "strong": {"rekt", "bagholder", "bags", "crashing", "dump", "rug", "rugpull", "down bad",
               "bled out", "liquidated", "suicide stack", "ngmi", "paper hands sell"},
    "medium": {"dead cat", "fake pump", "exit scam", "short ladder", "hedgies", "citadel"}
}

MEME_TICKER_BOOST = {"GME", "AMC", "BBBY", "SPCE", "KOSS", "EXPR", "NAK", "CLF", "PLTR", "SOFI", "HOOD", "RIVN", "LCID"}

SHORT_POSITION_KEYWORDS = {
    "puts", "put option", "put options", "bought puts", "shorting", "sold short",
    "short position", "bet against", "betting against", "bear put spread", "inverse etf"
}

FLAIR_LABEL_MAP = {
    "Gain": "Positive",
    "Loss": "Negative"
}

WSB_FEW_SHOT_EXAMPLES = [
    # Explicit long position, price rose -> Positive
    {
        "text": "Bought NVDA calls last week, up 40% since. Riding this to the moon.",
        "label": "Positive"
    },
    # Bullish thesis on an undervalued stock -> Positive
    {
        "text": "MSFT is way undervalued here given the earnings growth, loading up on shares.",
        "label": "Positive"
    },
    {
        "text": "Central bank cuts rates more than expected, markets about to rip.",
        "label": "Positive"
    },
    {
        "text": "Bought the dip on TSLA and it just kept dipping. Down 60% now.",
        "label": "Negative"
    },
    {
        "text": "Puts printed today. Thanks for crashing, AMC.",
        "label": "Negative"
    },
    {
        "text": "Manufacturing data comes in way below forecast, recession fears spiking.",
        "label": "Negative"
    },
    {
        "text": "Finally got a perfect score on something. My account balance: 0.00",
        "label": "Negative"
    },
    {
        "text": "Oh great, another 'transitory' dip, this is definitely going to the moon any day now",
        "label": "Negative"
    },
    {
        "text": "Company X announces it will raise $2B through a bond offering next quarter.",
        "label": "Neutral"
    },
    {
        "text": "Regulator opens a review into the merger between two mid-cap tech firms.",
        "label": "Neutral"
    },
    {
        "text": "Anyone else holding through earnings tomorrow or getting out now?",
        "label": "Neutral"
    },
]

WSB_SYSTEM_PROMPT = """{prompt}""".format(prompt='You are a financial sentiment classifier for Reddit r/WallStreetBets (WSB).\n\nYour task is to classify the sentiment expressed in a single post about a stock, ETF, or cryptocurrency.\n\nWSB posts often include slang, memes, sarcasm, and exaggerated financial language (e.g., YOLO, diamond hands, tendies, rekt, bagholder, rocket emojis 🚀).\n\nRules:\n- Interpret sarcasm and irony based on implied meaning, not literal wording.\n- Focus on sentiment toward the financial asset, not humor or meme content alone.\n- Ignore off-topic content unless it implies bullish or bearish sentiment.\n\nLabels (based ONLY on expected price direction of the asset — ignore the poster\'s tone, profit, or emotional state):\npositive: the post expresses or implies the asset\'s price will rise or has risen (bullish direction)\nnegative: the post expresses or implies the asset\'s price will fall or has fallen (bearish direction) — this includes short positions, puts, or bets against the asset, even if that bet was profitable or the poster sounds happy about it\nneutral: no clear directional expectation about price is expressed (pure facts, genuinely uncertain outcome, or no opinion at all)\n\nIMPORTANT:\n- A profitable trade is NOT automatically positive — a profitable short/put bet is negative, because it reflects a bearish view of the asset.\n- Return only one label (positive, neutral, or negative).\n- Do not explain your answer.\n- Do not output anything except the label.')


def _keyword_hints(text):
    """Returns found bullish/bearish slang-signals to send them to the prompt as context."""
    text_lower = str(text).lower()
    bullish = [kw for kw in BULLISH_MEME_KEYWORDS["strong"] | BULLISH_MEME_KEYWORDS["medium"] if kw in text_lower]
    bearish = [kw for kw in BEARISH_MEME_KEYWORDS["strong"] | BEARISH_MEME_KEYWORDS["medium"] if kw in text_lower]
    return bullish, bearish


def _build_prompt(target):
    bullish, bearish = _keyword_hints(target)
    hint_line = ""
    if bullish or bearish:
        hint_line = (f"\n\n(Detected slang signals — bullish: {bullish or 'none'}, "
                     f"bearish: {bearish or 'none'}. These are surface-level cues only — "
                     f"verify against actual price direction and sarcasm before using them.)")
    parts = [WSB_SYSTEM_PROMPT + hint_line, ""]
    for ex in WSB_FEW_SHOT_EXAMPLES:
        parts.append(f"Post: {ex['text']}\nSentiment: {ex['label']}")
    parts.append(f"Post: {target.strip()}\nSentiment:")
    return "\n\n".join(parts)


def _call_llm(prompt, client):
    for attempt in range(RETRY_LIMIT):
        try:
            response = client.responses.create(model=MODEL, input=prompt, temperature=0)
            raw = response.output_text.strip().capitalize()
            if raw in LABELS:
                return raw
            for label in LABELS:
                if label in raw:
                    return label
            return FAILURE_LABEL
        except RateLimitError:
            time.sleep(RETRY_DELAY * (attempt + 1))
        except APIError as e:
            print(f"[classifier] API error: {e}")
            time.sleep(RETRY_DELAY)
    return None


def _extract_ticker(text):
    match = re.search(r'\$([A-Z]{1,5})\b', str(text))
    return match.group(1) if match else None


def _get_client(client, api_key):
    if client is not None:
        return client
    key = api_key or os.environ.get("OPENAI_API_KEY")
    if not key:
        raise ValueError(
            "No OpenAI client or API key provided. Pass client=OpenAI(api_key=...) "
            "or set the OPENAI_API_KEY environment variable in Replit Secrets."
        )
    return OpenAI(api_key=key)


def _has_short_position_signal(text):
    """True if the text explicitly references a bearish-direction bet (puts, shorting, etc.)."""
    text_lower = str(text).lower()
    return any(kw in text_lower for kw in SHORT_POSITION_KEYWORDS)


def classify_post(text, flair=None, client=None, api_key=None):
    """Classify a single WSB post. Returns dict with sentiment, method, ticker, confidence."""
    ticker = _extract_ticker(text)
    if flair and flair in FLAIR_LABEL_MAP:
        if _has_short_position_signal(text):
            # A "Gain" flair with a puts/short signal means the bet was profitable,
            # but the bet itself was bearish — price direction is down, so Negative,
            # not the FLAIR_LABEL_MAP default. This is a rule override, not the LLM.
            return {"sentiment": "Negative", "method": "rules_based_short_override",
                     "ticker": ticker, "confidence": "high"}
        return {"sentiment": FLAIR_LABEL_MAP[flair], "method": "rules_based",
                 "ticker": ticker, "confidence": "high"}
    _client = _get_client(client, api_key)
    label   = _call_llm(_build_prompt(text), _client)
    return {"sentiment": label or FAILURE_LABEL, "method": "llm_judge",
             "ticker": ticker, "confidence": "model"}


def classify_dataframe(df, text_col="title", flair_col="flair", client=None, api_key=None):
    """Classify a full DataFrame. Adds sentiment, classification_method, ticker columns."""
    from tqdm.auto import tqdm
    _client = _get_client(client, api_key)
    results = []
    for _, row in tqdm(df.iterrows(), total=len(df), desc="Classifying"):
        text  = str(row.get(text_col, ""))
        flair = str(row.get(flair_col, "")) if flair_col else None
        results.append(classify_post(text, flair=flair, client=_client))
    out = df.copy()
    out["sentiment"]             = [r["sentiment"] for r in results]
    out["classification_method"] = [r["method"]    for r in results]
    out["ticker"]                = [r["ticker"]     for r in results]
    return out


def load_labeled_data(path=None):
    """Load the pre-labeled WSB dataset produced by Notebook 3."""
    if path is None:
        try:
            import model_setup
            path = model_setup.paths.get("wsb_labeled.csv")
        except ImportError:
            pass
    if path is None:
        path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "wsb_labeled.csv")
    if not os.path.exists(path):
        raise FileNotFoundError(f"wsb_labeled.csv not found at {path}.")
    df = pd.read_csv(path)
    if "date_utc" in df.columns:
        df["date_utc"] = pd.to_datetime(df["date_utc"], utc=True, errors="coerce")
    return df


def get_sentiment_summary(df, sentiment_col="sentiment"):
    """Return sentiment counts and percentages — useful for dashboard stat cards.

    Posts with FAILURE_LABEL (parsing/API failures, not real classifications) are
    excluded from the percentage denominator but reported separately so failures
    stay visible instead of silently skewing the Positive/Negative/Neutral split.
    """
    failed_mask  = df[sentiment_col] == FAILURE_LABEL
    failed_count = int(failed_mask.sum())
    valid        = df.loc[~failed_mask]
    counts       = valid[sentiment_col].value_counts()
    total        = len(valid)
    return {
        label: {"count": int(counts.get(label, 0)),
                "pct":   round(counts.get(label, 0) / total * 100, 1) if total else 0}
        for label in LABELS
    } | {
        "total": total,
        "unable_to_label_count": failed_count,
    }


def get_top_tickers(df, n=10):
    """Return top-n most-mentioned tickers with sentiment breakdown.

    FAILURE_LABEL rows are dropped before computing percentages (they aren't a
    real sentiment) but their count per ticker is kept as unable_to_label_count
    so failures don't get silently absorbed into Neutral or skew the split.
    """
    if "ticker" not in df.columns:
        df = df.copy()
        df["ticker"] = df.get("title", pd.Series(dtype=str)).apply(_extract_ticker)
    ticker_df = df.dropna(subset=["ticker"])
    if ticker_df.empty:
        return pd.DataFrame()
    rows = []
    for ticker, group in ticker_df.groupby("ticker"):
        failed_mask  = group["sentiment"] == FAILURE_LABEL
        failed_count = int(failed_mask.sum())
        valid_group  = group.loc[~failed_mask]
        counts       = valid_group["sentiment"].value_counts()
        total        = len(valid_group)
        rows.append({
            "ticker"                : ticker,
            "mention_count"         : len(group),
            "unable_to_label_count" : failed_count,
            "positive_pct"          : round(counts.get("Positive", 0) / total * 100, 1) if total else 0,
            "negative_pct"          : round(counts.get("Negative",  0) / total * 100, 1) if total else 0,
            "neutral_pct"           : round(counts.get("Neutral",   0) / total * 100, 1) if total else 0,
            "avg_score"             : round(group["score"].mean(), 1) if "score" in group else 0,
            "dominant_sentiment"    : counts.idxmax() if not counts.empty else "Unable to label",
        })
    return (pd.DataFrame(rows)
            .sort_values("mention_count", ascending=False)
            .head(n)
            .reset_index(drop=True))